added ice effective radius product from Griesche et al. 2020
actris-cloudnet/cloudnetpy pull request #51
Opened 2022-05-18 10:41 UTC by KarlJohnsonnn

Adding the ice effective radius product from Griesche et al. 2020.

2022-05-19 13:00 UTC, KarlJohnsonnn commented
Hi, 

I need help, somehow the checks were not successful, see:

`Run mypy --ignore-missing-imports cloudnetpy/ tests/
[6](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:7)
cloudnetpy/products/ier.py:325: error: Argument "comment" to "MetaData" has incompatible type "Sequence[str]"; expected "Optional[str]"
[7](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:8)
cloudnetpy/products/ier.py:331: error: Argument "comment" to "MetaData" has incompatible type "Sequence[str]"; expected "Optional[str]"
[8](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:9)
cloudnetpy/products/ier.py:335: error: Argument "comment" to "MetaData" has incompatible type "Sequence[str]"; expected "Optional[str]"
[9](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:10)
cloudnetpy/products/ier.py:342: error: Argument "comment" to "MetaData" has incompatible type "Sequence[str]"; expected "Optional[str]"
[10](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:11)
Found 4 errors in 1 file (checked 100 source files)
[11](https://github.com/actris-cloudnet/cloudnetpy/runs/6507336127?check_suite_focus=true#step:6:12)
Error: Process completed with exit code 1.`


I used the same notation as for iwc.py comments, a dict with key and tuple of comments. Not sure why it fails here but not in `der` or other products.

2022-05-19 13:03 UTC, tukiains commented
I believe you need to at least `git rebase master` and to fix merge conflicts first.

2022-05-19 13:35 UTC, KarlJohnsonnn commented
I did `git rebase master` and followed along. The merge conflicts were resolved and changes are pushed but still checks are not successful?

2022-05-20 06:11 UTC, siiptuo requested changes

2022-05-20 06:11 UTC, siiptuo commented on cloudnetpy/products/ier.py
> +        "The most reliable retrieval is that without any rain or liquid\n",
There's a misplaced comma here and fixing this should fix the type error:
```suggestion
        "The most reliable retrieval is that without any rain or liquid\n"
```

2022-05-20 06:11 UTC, siiptuo commented on cloudnetpy/products/ier.py
> +        "ice water content when rain is present below the ice; this is\n"
The last sentence seems to be cut off: "this is..."

2022-05-20 07:31 UTC, tukiains commented
The errors come from the `cloudnetpy-qc` package. We are fixing these right now.. Let's see if the tests pass soon.

2022-05-20 08:00 UTC, KarlJohnsonnn commented
@siiptuo Thanks for spotting the typos! It seems to work now.

2022-05-20 08:10 UTC, tukiains commented
Great! We well take a closer look at it now.

2022-05-20 11:33 UTC, merged

2022-05-20 11:33 UTC, tukiains commented
Thanks again @KarlJohnsonnn! Good work! :+1: