Add support for Copernicus cloud radar
actris-cloudnet/cloudnetpy pull request #61
Opened 2022-08-16 10:34 UTC by tukiains

2022-08-16 13:40 UTC, nikoleskinen requested changes

2022-08-16 13:40 UTC, nikoleskinen commented on cloudnetpy/instruments/nc_radar.py
> +    def add_solar_angles(self) -> list:
`solar` veks. Esim: `angles`, `coordinates`, `coordinate_angles` tai `celestial_coordinates`

2022-08-16 13:40 UTC, nikoleskinen commented on cloudnetpy/instruments/nc_radar.py
> +        if n_removed >= len(zenith) - 1:
`n_removed == len(zenith)`

2022-08-16 13:40 UTC, nikoleskinen commented on cloudnetpy/instruments/basta.py
>          """Adds solar zenith and azimuth angles and returns valid time indices."""
`solar` ?

2022-08-17 08:47 UTC, tukiains commented on cloudnetpy/instruments/nc_radar.py
> +    def add_solar_angles(self) -> list:
Hyvä huomio.

2022-08-17 09:53 UTC, tukiains commented on cloudnetpy/instruments/nc_radar.py
> +        if n_removed >= len(zenith) - 1:
Tarvitaan vähintään 2 profiilia. Muutan lokiviestin.

2022-08-17 09:53 UTC, tukiains commented on cloudnetpy/instruments/basta.py
>          """Adds solar zenith and azimuth angles and returns valid time indices."""
Joo, tää pitää korjata kaikkialle.

2022-08-17 16:49 UTC, merged